# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json
backend:
  name: github
  repo: stephenbarkan/mustafa

media_folder: /assets/uploads
public_folder: /assets/uploads

singletons:
  - name: global
    label: Global Site Data
    file: /_data/global.json
    icon: public
    fields:
      - label: Site Domain
        name: siteDomain
        widget: string
      - label: Site Title
        name: siteTitle
        widget: string
      - label: Site Description
        name: siteDescription
        widget: string
      - label: Share Image
        name: siteImage
        widget: image
      - label: Browser Icon
        name: favicon
        widget: image
  - name: navLinks
    label: Navigation Links
    file: /_data/navLinks.json
    icon: link
    fields:
      - label: Links
        name: siteDomain
        widget: list
        root: true
        fields:
          - label: Label
            name: label
            widget: string
          - label: URL
            name: href
            widget: string
  - name: homepage
    label: Home page
    file: /_data/homepage.json
    icon: home
    fields:
      - label: Photos
        name: photos
        widget: list
        required: true
        fields:
          - label: Image
            name: image
            widget: image
          - label: Alt Text
            name: altText
            widget: string
          - label: Aspect ratio
            name: aspect
            widget: select
            default: base
            options:
              - "4:5"
              - "8:5"
  - name: sponsorsGear
    label: Sponsors and Gear page
    file: /page/sponsors-gear.md
    icon: wand_stars
    fields:
      - name: layout
        widget: hidden
        default: "layouts/page.njk"
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: richtext
        buttons: [heading-two, heading-three, bulleted-list, numbered-list, quote]
  - name: contactPage
    label: Contact page
    file: _data/contactPage.json
    icon: mail
    fields:
      - label: Title
        name: title
        widget: string
      - name: nameField
        label: Name field
        widget: object
        fields:
          - name: label
            label: Label
            widget: string
          - name: description
            label: Description
            required: false
      - name: contactMethodField
        label: Contact method field
        widget: object
        fields:
          - name: label
            label: Label
            widget: string
          - name: description
            label: Description
            required: false
      - name: messageField
        label: Message field
        widget: object
        fields:
          - name: label
            label: Label
            widget: string
          - name: description
            label: Description
            required: false

collections:
  - name: offerings
    label: Offerings
    folder: /offering
    icon: comedy_mask
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: richtext
        buttons: [heading-two, heading-three, bulleted-list, numbered-list, quote]
      - label: Photos
        name: photos
        widget: list
        required: false
        fields:
          - label: Image
            name: image
            widget: image
          - label: Caption
            name: caption
            widget: string
