# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json
backend:
  name: github
  repo: stephenbarkan/mustafa

media_folder: /assets/uploads
public_folder: /assets/uploads

collections:
  - name: artforms
    label: Artforms
    folder: /artform
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: richtext
      - label: Photos
        name: photos
        widget: list
        required: false
        fields:
          - label: Image
            name: image
            widget: image
          - label: Caption
            name: caption
            widget: string
