# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json
backend:
  name: github
  repo: stephenbarkan/mustafa

media_folder: /assets/uploads
public_folder: /assets/uploads

singletons:
  - label: Global Site Data
    name: global
    file: /_data/global.json
    icon: public
    fields:
      - label: Site Domain
        name: siteDomain
        widget: string
      - label: Site Title
        name: siteTitle
        widget: string
      - label: Site Description
        name: siteDescription
        widget: string
      - label: Share Image
        name: siteImage
        widget: image
      - label: Browser Icon
        name: favicon
        widget: image
collections:
  - label: Pages
    name: pages
    icon: stacks
    files:
      - label: Home
        name: homepage
        file: /_data/homepage.json
        icon: home
        fields:
          - label: Photos
            name: photos
            widget: list
            required: true
            fields:
              - label: Image
                name: image
                widget: image
              - label: Alt Text
                name: altText
                widget: string
              - label: Aspect ratio
                name: aspect
                widget: select
                default: base
                options:
                  - "4:5"
                  - "8:5"
  - label: Artforms
    name: artforms
    folder: /artform
    icon: wand_shine
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: richtext
      - label: Photos
        name: photos
        widget: list
        required: false
        fields:
          - label: Image
            name: image
            widget: image
          - label: Caption
            name: caption
            widget: string
